##
## Auth Service ? Application Properties
##
## Syfte: Bestämmer på vilken port Auth?tjänsten lyssnar. Övriga värden är
## standard i denna demo. BFF använder denna port som bas?URL för /api/login.

# HTTP?port för Auth?tjänsten
server.port=8081
