##
## User Service ? Application Properties
##
## Syfte: Anger HTTP?porten för User?tjänsten. BFF proxar /api/users...
## vidare till denna tjänst på angiven port.

# HTTP?port för User?tjänsten
server.port=8082
